### ISSUE TITLE
Move to Control.Monad.ListT

### ISSUE THREAD

**Issue by gleber** [nikita-volkov/list-t#1]
Or somewhere else, which is not top-level. Top-level module looks at least inconsistent with everything else.

**Comment by andreasabel** [comment]
I think it should anyway be in one of `Data.ListT`, `Control.Monad.ListT` or `Control.Monad.Trans.List`.  Top-level looks worst.

**Comment by massysett** [comment]
FWIW - I agree with a simple ListT; the littering of `Control.Monad.xxx` and `Text.ParserCombinators.xxx` and `Text.xxx` and `Data.xxx` is useless.
