### ISSUE TITLE
Instance of MonadTransControl?

### ISSUE THREAD

**Issue by polux** [nikita-volkov/list-t#13]
I'm not sure that's actually possible but could ListT have a instance of MonadTransControl?

**Comment by nikita-volkov** [comment]
Not sure 🤔

**Comment by polux** [comment]
The thing that makes me doubt it can in addition to not seeing how it could be done is that the MonadTransControl doc says:

> Instances are based on monad transformers in MonadTransControl, which includes all standard monad transformers in the transformers library except ContT.

And ListT is somewhat reminiscent of ContT.

**Comment by treeowl** [comment]
@polux, how is it reminiscent of `ContT`?

**Comment by treeowl** [comment]
Note that it's possible to write a lawful instance for `FreeT`, and I think this is closer to that.

**Comment by polux** [comment]
I honestly don't remember why I wrote that :) I think my reasoning was that you can do logic programming in ListT as well as in ContT. But cont is "the mother of all monads" so that's not very surprising and doesn't say much.

**Comment by treeowl** [comment]
I just looked at this a bit more, and I don't think it's possible. The trouble is that `StT ListT a` should be `Maybe (a, ListT m a)`, but there's nowhere for that `m` to come from. It might be possible to change the definition of `MonadTransControl` to make it work with these sorts of transformers, but I'm pretty sure it doesn't right now.
