### ISSUE TITLE
Bring back fromListT stuff

### ISSUE THREAD

**Issue by treeowl** [nikita-volkov/list-t#18]
These are primarily for left distribution `MonadPlus` instances, not left catch ones!

**Comment by nikita-volkov** [comment]
Right! Forgot about that :) Apologies.

I still however find those functions too specific. In https://github.com/nikita-volkov/list-t/commit/0fe2943978ef7861e91ebb2d4a57eb1d429758f4 I've extracted a simpler function from your `fromListTWith`. Now

```haskell
fromListTWith f = alternate . hoist f
```

What do you think about that?

**Comment by treeowl** [comment]
I personally prefer the more general version, which can implement `alternate` more efficiently than the other way around. Also, `MonadPlus` is a bit overkill these days.

**Comment by treeowl** [comment]
I do think your `alternate` is clever, but (aside from a difference in constraints)

```haskell
hoist f = fromlistT (lift . f)
```

so it's not a one-trick pony.

**Comment by treeowl** [comment]
Whoops, last comment edited.

**Comment by nikita-volkov** [comment]
The MonadPlus remark accepted: https://github.com/nikita-volkov/list-t/commit/fc77244daf85c4d9ad41e5a8a3b8c36e316022ba

**Comment by nikita-volkov** [comment]
Regarding the efficiency, it can be solved with rewrite rules without burdening the user with specific functions.

**Comment by treeowl** [comment]
When considering converting from ListT to SeqT in the brand-new
logict-sequence package, I suspect very few will immediately realize they
should alternate and hoist. And the ones that do will see that they're
wasting time in two operations and then write their own custom conversion.
This does not bring me joy. I want my fromListTWith! (By any name.)

**Comment by treeowl** [comment]
Rewrite rules are really tricky in this space, because they tend to rely on
monads and monad morphisms being strictly lawful (no room even for laziness
variations). We could try, but it's probably going to be a bit tricky.

**Comment by nikita-volkov** [comment]
Ok. https://github.com/nikita-volkov/list-t/commit/73c842bda3adcf209b298b143e983f532048c612
