### ISSUE TITLE
Stop using liftM

### ISSUE THREAD

**Issue by treeowl** [nikita-volkov/list-t#20]
For some monads (e.g., `Data.Sequence.Seq`), `fmap` is considerably faster than `liftM`. We should use `fmap` instead. I'm guessing `liftM` might be used here to signal that the underlying monad is being mapped over, in which case maybe we should come up with an alternative name for `fmap`.

**Comment by nikita-volkov** [comment]
There's no real reason to use liftM here. It's likely a historic artefact. So I'm pro to this suggestion.
