### ISSUE TITLE
Make a release?

### ISSUE THREAD

**Issue by treeowl** [nikita-volkov/list-t#26]
I have only a few more PRs left and then I'm mostly out of easy stuff. I suspect there's been enough progress since the last release to make a new one worthwhile.

**Comment by nikita-volkov** [comment]
Yep. Let's clear up the status on all PRs and I'll make a release

**Comment by nikita-volkov** [comment]
1.0.5 released.

**Comment by nikita-volkov** [comment]
Thanks for your major contribution!
