### ISSUE TITLE
Reducing dependencies with conditional flag

### ISSUE THREAD

**Issue by ivanperez-keera** [nikita-volkov/list-t#34]
Hi,

The package `dunai` uses the old `ListT` transformer, which is deprecated/gone.

We are considering to use `list-t`. However, `list-t` has lots of dependencies, for the most part due to the desire to provide many instances.

In our case, the difference between using `list-t` and not using it is this: https://github.com/ivanperez-keera/dunai/discussions/368#discussioncomment-7283147

Would you be willing to introduce a flag that hides most dependencies on packages, several instances, and `applyFoldM`, such that the only dependencies of the library are `base` and `transformers`? The flag would default to producing the current behavior, so that no users are negatively affected, but it would give us the ability to remove those dependencies during installation.

**Comment by nikita-volkov** [comment]
Hi. That would add maintenance burden yet the benefits escape me. Most of the packages depended on are highly likely to get transitively depended on by most applications any way, also I don't see how you would reduce the transitive deps of "dunai" as a package. How do you plan to control that flag?

**Comment by ivanperez-keera** [comment]
I understand.

If you look at that comment I left, and the ones that follow, you'll see that `dunai` depends on very few packages.

I just took a look at a real application using dunai and added `list-t` as a dependency. That, in turn, adds:
```
assoc-1.1
bifunctors-5.6.1
comonad-5.0.8
contravariant-1.5.5
distributive-0.6.2.1
foldable1-classes-compat-0.1
foldl-1.4.15
hashable-1.4.3.0
indexed-traversable-0.1.2.1
list-t-1.0.5.1
logict-0.7.0.3
mmorph-1.2.0
monad-control-1.0.3.1
profunctors-5.6.2
semigroupoids-6.0.0.1
semigroups-0.20
StateVar-1.2.2
tagged-0.8.8
th-abstraction-0.6.0.0
unordered-containers-0.2.19.1
vector-0.13.0.0
vector-stream-0.1.0.0
```

During installation, we could simply state that the library `list-t` can be installed with the flag `-f-minimal` (to call it something). The installation tools we have allow us to specify flags per package.

**Comment by nikita-volkov** [comment]
So the end user will have to specify the flag. I think it'll be only handful of users who would care about the dependency list enough to explicitly limit them via flags. So I don't think it's worth adding the maintenance burden.

However I must inform you that there exists an alternative to this package which has fewer deps: https://hackage.haskell.org/package/list-transformer

**Comment by ivanperez-keera** [comment]
I see.

Thanks for the pointer to `list-transformer`. I'll check it out.
