### ISSUE TITLE
bad upper bounds: everything below 0.4.3 breaks with base-prelude-0.1.16

### ISSUE THREAD

**Issue by lspitzner** [nikita-volkov/list-t#4]
specifically multiple instances of

~~~~
library/ListT.hs:83:7:
    Ambiguous occurrence ‘uncons’
    It could refer to either ‘ListT.uncons’,
                             defined at library/ListT.hs:134:3
                          or ‘BasePrelude.uncons’,
                             imported from ‘BasePrelude’ at library/ListT.hs:30:1-100
~~~~

(i noticed this because i had a list-t < 0.3 dependency, and did a fresh sandbox install, which chose base-prelude-0.1.16 and list-t-0.2.6)

**Comment by lspitzner** [comment]
the "right" fix seems to be to re-write the upper bounds of all the previous releases. but that is a somewhat annoying amount of work.. i wonder if there is a better approach (because, in general, i have the same strategy regarding my upper bounds, i.e. to allow everything below next major version, which causes problems here).
~~~~
 base-prelude == 0.1.*
~~~~

**Comment by nikita-volkov** [comment]
Thanks. Fixed in "list-t" 0.2.7.

**Comment by lspitzner** [comment]
ah, so you chose to create a fixed minor version for each relevant major version. interesting solution.

**Comment by lspitzner** [comment]
and thanks for the quick fix!
