### ISSUE TITLE
Making ListT's constructors available

### ISSUE THREAD

**Issue by jwiegley** [nikita-volkov/list-t#6]
Hello, can you please export `ListT`'s constructor?  I'd rather use your type than roll yet another version of `ListT`, and I want to be able to access the constructor directly.  Thanks.

**Comment by nikita-volkov** [comment]
Hi. The library exposes the `uncons` function, which does what you must be looking for.

**Comment by jwiegley** [comment]
Is there a particular reason to hide the constructor?

**Comment by nikita-volkov** [comment]
Not to provide multiple ways of doing the same thing.

**Comment by jwiegley** [comment]
@nikita-volkov I guess I'll just use my own version of the type then, thanks.

**Comment by nikita-volkov** [comment]
Ok. BTW, what was the reason stopping you from using the `uncons` function?

**Comment by jwiegley** [comment]
I'd rather avoid engaging type classes for something so basic that will be done often.  It feels too much like over-design to me, since I just wanted `ListT`, not a generalized mechanism for cons'ing and unions'ing to and from list-like constructions.

**Comment by nikita-volkov** [comment]
Well, that I agree with. I actually do have a plan to simplify the API by removing the type-classes in the future version, as soon as I get my hands on it. 

BTW, I also plan to switch the implementation from `m (Maybe (a, ListT m a))` to `Maybe (a, ListT m a)`, since it's more general.

**Comment by jwiegley** [comment]
How would you represent an effect that produces `[]`?

**Comment by nikita-volkov** [comment]
In the function, which produces the `ListT`. E.g., 
```haskell
streamFile :: FilePath -> ListT IO Text
```
will turn into
```haskell
streamFile :: FilePath -> IO (ListT IO Text)
```

I'm open for debate on that however.

**Comment by jwiegley** [comment]
How does `Maybe (a, ListT m a))` use `m` at all?  What happens to the behavior of composition?

**Comment by nikita-volkov** [comment]
Oh, right. What I meant was `Maybe (a, m (ListT m a))`.

**Comment by jwiegley** [comment]
One major semantic difference between the two would be when effects happens.  If I'm given a `ListT m a` value of the current type, it means I need to cause an effect in m to see what the next value is.  With the new type, that effect has always been processed before I'm given the `ListT m a` value.  I can imagine there are cases where this is good, and cases where it's not good.  It's definitely not how all the existing transformers work, where "running" the transformer must be done within the `Monad` `m`.

**Comment by jwiegley** [comment]
Consider also a `ListT m a` where a is a huge value (many megabytes).  In the current code, that cost is paid and then release at the point of use, since `ListT m a` is an action for producing values and future actions.  With your proposed change, the memory of the most recent element is not freed until the last `ListT m a` is garbage collected, because now `ListT m a` is both a container, and an action for producing new containers.  I don't like this kind of "mixed semantics" at all.  I want `ListT m a` to be a means for generating elements, not a cache for an element, plus a generation process.

**Comment by jwiegley** [comment]
I suppose the most succinct way to put this is that the types are not isomorphic; they're not even adjoint.

**Comment by nikita-volkov** [comment]
Before I go on, for clarity in further discussion I suggest to use the following names:

```haskell
-- | The current implementation
newtype ListT1 m a = ListT1 (m (Maybe (a, ListT1 m a)))

-- | The proposed implementation
newtype ListT2 m a = ListT2 (Maybe (a, m (ListT2 m a)))
```

> One major semantic difference between the two would be when effects happens. If I'm given a ListT m a value of the current type, I need to cause an effect in m to see what the next value is. With the new type, that effect has already been processed before I'm given the ListT m a value.

Sure, the types `ListT1` and `ListT2` are not semantically equivalent. But `ListT1 m a` and `m (ListT2 m a)` are. So you can use the latter composed type to reproduce the current behaviour.

My original intention with the `ListT2` idea was that it's API would provide for a more fine-grained control and would still be easily liftable into the behaviour of `ListT1` using the standard monadic/functorial combinators.

I guess the factors that motivated me the most were that in the current API it's impossible to implement head-checks, which do not consume the input. E.g., the `null` funnction consumes the input. Also as I recall, in Scala the Stream (lazy list) type is implemented in a similar way, where its head is strict and the tail is lazy ([if we consider laziness as an effectful monad](http://nikita-volkov.github.io/if-haskell-were-strict/)). I just thought there must have been some good reason for them to implement it that way.

> It's definitely not how all the existing transformers work, where "running" the transformer must be done within the Monad m.

Consistency with other transformers is definitely a good argument. However, you can notice that most of the ListT's API is about different ways of "running" it, which is not common throughout other transformers.

> a cache for an element, plus a generation process.

I guess that's the clearest way to describe the proposed change.

---

Either way, thanks to your comments I'm now convinced that it's too controversial of a change to commit until a serious investigation of the subject. So the next major version definitely won't contain that change, and if one is to ever do it will only be after a poll of the user-base.

As for the subject issue, if you're willing to simplify the current API before I get my hands on it, I'm all open for PRs.
